### ISSUE TITLE
MXNet 1.5 container

### ISSUE THREAD

**Issue by eric-haibin-lin** [aws/sagemaker-mxnet-training-toolkit#109]
Will MXNet 1.5 sagemaker container be released?

**Comment by zeeshansayyed** [comment]
Any update on this will be greatly appreciated. Can you atleast point in the necessary changes required for supporting mxnet 1.5?

**Comment by JohnCalhoun** [comment]
I updated MX_VERSION=1.5.1 and everything worked fine

**Comment by laurenyu** [comment]
The Dockerfiles have been moved to https://github.com/aws/deep-learning-containers
