### ISSUE TITLE
Container Support for Gluon Toolkits

### ISSUE THREAD

**Issue by szha** [aws/sagemaker-mxnet-training-toolkit#111]
Reference: 0413477381

The Gluon toolkits (GluonCV, GluonNLP, GluonTS) are the essential constituents of the MXNet ecosystem. Being a container for MXNet, and given that even packages outside of the ecosystem such as scikit-learn and pandas are included, shall we make sure we add these toolkits in the next release?

**Comment by szha** [comment]
Related one year old issue #31

**Comment by ChoiByungWook** [comment]
For reference: 0413477381

**Comment by junrushao1994** [comment]
This is super important to have gluon-nlp, gluon-cv and DGL built-in for the mxnet ecosystem

**Comment by Christopheraburns** [comment]
I could have used this at a workshop at re:mars.  I had to !pip install instead and I feel the solution could be cleaner.  Would love to see the built-in containers incorporate the latest Gluon developments.

**Comment by KarthikSonti** [comment]
+1 that it makes life easier for my customers  to have Gluon toolkit as part of SageMaker MxNet dockers

**Comment by dbtorrance** [comment]
+1 Absolutely this should be included, given the usefulness of these Gluon for mxnet users.

**Comment by guangyangai** [comment]
+1 supporting this feature.

**Comment by phiamazon** [comment]
+1 gluon makes developing mxnet model so much easier!

**Comment by umutisik** [comment]
+1000

**Comment by angelarw** [comment]
+1

**Comment by jamiekang** [comment]
+1

**Comment by muhyun** [comment]
+1

**Comment by hetong007** [comment]
+1

**Comment by YashalShakti** [comment]
+1

**Comment by zheng-da** [comment]
+1

**Comment by whamza15** [comment]
+1

**Comment by giuseppeporcelli** [comment]
+1

**Comment by w601sxs** [comment]
+1

**Comment by laurenyu** [comment]
The Dockerfiles have now been moved to https://github.com/aws/deep-learning-containers. Please open an issue in that repository so that the right team gets the feature request.
