### ISSUE TITLE
Information about Building with Elastic Inference is removed from readme.rst

### ISSUE THREAD

**Issue by pcolazurdo** [aws/sagemaker-mxnet-training-toolkit#170]
Hi team, can you check why the information provided in "Building the SageMaker Elastic Inference MXNet container" https://github.com/aws/sagemaker-mxnet-container/blob/e8f4a6a7904541fb4a651bb7d86b5c85496abb67/README.rst#building-the-sagemaker-elastic-inference-mxnet-container is removed in latest versions?
This link (https://github.com/aws/sagemaker-mxnet-container#building-the-sagemaker-elastic-inference-mxnet-container) is still referred in: https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html
Thanks

**Comment by ChuyangDeng** [comment]
Hi @pcolazurdo , thanks for using SageMaker!

Yes, we've separated the mxnet-training and mxnet-inference containers. The information you are looking for is now in [sagemaker-mxnet-serving-container](https://github.com/aws/sagemaker-mxnet-serving-container) and the "Building the SageMaker Elastic Inference MXNet container" is here: https://github.com/aws/sagemaker-mxnet-serving-container#amazon-elastic-inference-with-mxnet-in-sagemaker

**Comment by pcolazurdo** [comment]
Thanks for the answer, I'll open a PR for the AWS doc team to fix the link in the https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html page unless you have access to it too?
