### ISSUE TITLE
build args to specify additional python packages and cuda version

### ISSUE THREAD

**Issue by opringle** [aws/sagemaker-mxnet-training-toolkit#32]
I'm no docker wizard but if this was possible then #31 could be achieved through modifying the build command, rather than creating new Dockerfiles.

Unsure how to implement but I imagine something like:

Build the base image 
`docker build -t mxnet-base:1.2.1-gpu-py3 --build-arg cuda=9.2 -f Dockerfile.gpu .`

Build the final image
`docker build -t mxnet-gluonnlp-cu92:1.2.1-gpu-py3 --build-arg cuda=9.2 --build-arg additional_packages=pandas,gluonnlp -f Dockerfile.gpu .`

**Comment by laurenyu** [comment]
The Dockerfiles have now been moved to https://github.com/aws/deep-learning-containers
